### PR TITLE
Created start.bat/start.sh and folder 'worldanvil' + edited README.md

### PR DESCRIPTION
**Pull request by keithkfng**
You can now start the converter with start.bat. Edited the README file for more user-friendly instructions to use the converter. Output of .mca files now go towards the folder worldanvil.

EDIT: I've also just created start.sh for all platforms to start the converter.

### CODE REVIEW

**Comment by legoboy0215** [comment]
:+1:

**Comment by keithkfng** [comment]
I'll see how I go, and yes, you are correct. I should probably make this available to all platforms.

**Comment by legoboy0215** [comment]
Neat!

**Comment by ljyloo** [comment]
Thanks for your help!

**Pull request merged**
