### PR TITLE
Add support for 1.2+ worlds

### LINKED ISSUE #34: Are you sure it works with Minecraft PE 1.2.1?
I copied over a Minecraft PE 1.2.1 world from my iPad 4th generation running iOS 10.3.3, and this is what appears in the log. The CMD window opens up for about a second before closing again, even after I tried executing it with the Java command. A lot of other people are also saying that it doesn't work with Minecraft 1.2.1.
[log.txt](https://github.com/ljyloo/LevelDb2Avnil/files/1358020/log.txt)

### PR DESCRIPTION
**Pull request by 0x9fff00**
Adds support for Zlib raw compression using updated leveldb from https://github.com/0x9fff00/leveldb

Fixes #34

### CODE REVIEW

**Comment by gothic3** [comment]
Good day, I'm planning my project, I was building a map on version 1.2.8 mcpe, I would like to ask you for help in porting the Anvil card to the PC, I just can not bluff what and how to do the files, please be of help, I waited your converter for a year.

**Comment by BadCivets** [comment]
Me too

**Comment by hstr0100** [comment]
For 1.2+ As far as I'm aware, you have to ignore reading the skylight and blocklight arrays (4096 => 2048) because MCPE now calculates them on the fly (Which sucks for many reasons, but whatever).

This is the output that your updated version produces BTW:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.ljyloo.PE2PC.ConvertSource.convertSubChunk(ConvertSource.java:127)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:102)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:35)

**Comment by 0x9fff00** [comment]
@hstr0100 That error doesn't happen for me. Do you have a world that I can test on?

**Comment by Aarkena** [comment]
Hey there, I have the same problem as user hstr0100. Server log doesn't show much 

--START OF LOG--
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.ljyloo.PE2PC.ConvertSource.convertSubChunk(ConvertSource.java:127)
	at com.ljyloo.PE2PC.PE2PC.convert(PE2PC.java:102)
	at com.ljyloo.PE2PC.PE2PC.main(PE2PC.java:35)
--END OF LOG--

I'm kind of new here and tried my best. But I can't get to convert my world. I get that log and nothing in the "Worldanvil" folder. I've attached my "world" as of now (it's only a small world which I started to work on with my son, now he want's friends to play with him in this world so I started a PocketMine Server at home, but I can't seem to convert the world .. ) 

Thanks for your time and effort, I hope solving this might end up in helping others too! 
[World.zip](https://github.com/ljyloo/LevelDb2Avnil/files/2160937/World.zip)

**Pull request merged**
